# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 558)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(500, 0, 231, 531))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.Button_ReadModel = QtWidgets.QPushButton(self.centralwidget)
        self.Button_ReadModel.setGeometry(QtCore.QRect(370, 356, 100, 50))
        self.Button_ReadModel.setObjectName("Button_ReadModel")
        self.Button_Train = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Train.setGeometry(QtCore.QRect(370, 148, 100, 50))
        self.Button_Train.setObjectName("Button_Train")
        self.Button_SaveModel = QtWidgets.QPushButton(self.centralwidget)
        self.Button_SaveModel.setGeometry(QtCore.QRect(370, 304, 100, 50))
        self.Button_SaveModel.setObjectName("Button_SaveModel")
        self.Button_StopTrain = QtWidgets.QPushButton(self.centralwidget)
        self.Button_StopTrain.setGeometry(QtCore.QRect(370, 252, 100, 50))
        self.Button_StopTrain.setObjectName("Button_StopTrain")
        self.Button_LoadModel = QtWidgets.QPushButton(self.centralwidget)
        self.Button_LoadModel.setGeometry(QtCore.QRect(370, 200, 100, 50))
        self.Button_LoadModel.setObjectName("Button_LoadModel")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于特征处理的手写数字识别"))
        self.Button_ReadModel.setText(_translate("MainWindow", "模型读取"))
        self.Button_Train.setText(_translate("MainWindow", "神经网络训练"))
        self.Button_SaveModel.setText(_translate("MainWindow", "模型保存"))
        self.Button_StopTrain.setText(_translate("MainWindow", "训练强制停止"))
        self.Button_LoadModel.setText(_translate("MainWindow", "网络模型导入"))
